on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build Android Release"

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    # FIX 1: Explicitly grant write permissions to this job
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.1'
          
      - name: Get Flutter dependencies
        run: flutter pub get
        
      - name: Build Android APK
        run: flutter build apk --debug --split-per-abi 

      - name: Upload APKs to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*" 
          tag: v1.0.${{ github.run_number }}
          # FIX 2: Use the default GITHUB_TOKEN instead of a custom secret
          token: ${{ secrets.GITHUB_TOKEN }}